/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#0e0e0e",
        "tertiary-container": "#c6c7c7",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-container": "#515353",
        "outline-variant": "#44464f",
        "surface-container-high": "#2a2a2a",
        "on-secondary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "tertiary-fixed": "#e2e2e2",
        "error": "#ffb4ab",
        "on-primary": "#162f5e",
        "primary-fixed": "#d9e2ff",
        "inverse-surface": "#e5e2e1",
        "surface-container-low": "#1c1b1b",
        "on-primary-fixed": "#001944",
        "secondary-container": "#474746",
        "on-surface-variant": "#c5c6d0",
        "surface-dim": "#131313",
        "tertiary": "#e3e3e3",
        "primary": "#d9e2ff",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-bright": "#3a3939",
        "surface": "#131313",
        "on-secondary": "#313030",
        "surface-tint": "#b0c6ff",
        "outline": "#8e909a",
        "on-secondary-container": "#b7b5b4",
        "secondary": "#c8c6c5",
        "primary-container": "#b0c6ff",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#2f3131",
        "on-error": "#690005",
        "background": "#131313",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "on-secondary-fixed": "#1c1b1b",
        "inverse-primary": "#475d90",
        "secondary-fixed-dim": "#c8c6c5",
        "on-primary-container": "#3b5183",
        "surface-container-highest": "#353534",
        "primary-fixed-dim": "#b0c6ff",
        "on-tertiary-fixed": "#1a1c1c",
        "on-primary-fixed-variant": "#2f4576"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem"
      },
      spacing: {
        base: "4px",
        "grid-margin": "32px",
        "grid-gutter": "24px",
        xs: "8px",
        md: "24px",
        lg: "40px",
        xl: "80px",
        sm: "16px"
      },
      fontFamily: {
        "headline-lg": ["Geist"],
        "body-md": ["Geist"],
        "headline-lg-mobile": ["Geist"],
        "label-code": ["JetBrains Mono"],
        "label-caps": ["JetBrains Mono"],
        "headline-xl": ["Geist"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", letterSpacing: "0em", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-code": ["14px", { lineHeight: "1.4", letterSpacing: "0.05em", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
